FROM debian:jessie
MAINTAINER Roman Galeev <jamhed@2600hz.com>

ENV DEBIAN_FRONTEND noninteractive
ENV APT_LISTCHANGES_FRONTEND=none

WORKDIR "/root"

COPY etc/sources.list /etc/apt

COPY build/setup-os.sh build/setup-os.sh
RUN build/setup-os.sh

COPY build/setup-erlang.sh build/setup-erlang.sh
RUN build/setup-erlang.sh

ENV BASH_ENV .bashrc
COPY etc/profile .bashrc

COPY build/setup-bin.sh build/setup-bin.sh
RUN build/setup-bin.sh

COPY build/cleanup.sh build/cleanup.sh
RUN build/cleanup.sh
